In [1]:
import numpy as np
from scipy.io import loadmat

def rq_decompose(M):
    """
    Perform RQ decomposition on a 3x3 matrix M.
    Returns K (upper triangular) and R (orthogonal) such that M = K @ R.
    """
    n = M.shape[0]
    p = np.fliplr(np.eye(n))
    # Flip matrix and perform QR decomposition
    Q_flip, R_flip = np.linalg.qr(p @ M.T @ p)
    K = p @ R_flip.T @ p
    R = p @ Q_flip @ p
    return K, R.conj().T

def normalize_K(K):
    """
    Normalize the calibration matrix so that K[2,2] = 1,
    and ensure all diagonal elements are positive.
    """
    K = K / K[2, 2]
    for i in range(3):
        if K[i, i] < 0:
            K[:, i] *= -1
    return K

def main():
    # Load the .mat file
    data = loadmat('data.mat')

    # Extract the first camera's projection matrix P (3x4)
    P = data['P'][0, 0]  # Adjust indexing based on the structure of your .mat file

    # Extract the 3x3 submatrix (K * R)
    M = P[:, :3]

    # Perform RQ decomposition to get K and R
    K, R = rq_decompose(M)

    # Normalize K
    K = normalize_K(K)

    # Save K to a text file
    np.savetxt('K.txt', K, fmt='%.6f')

    print("Camera Calibration Matrix K:")
    print(K)

if __name__ == '__main__':
    main()

Camera Calibration Matrix K:
[[ 2.46907447e+03  7.10542736e-13  9.76773452e+02]
 [ 0.00000000e+00  2.49523328e+03  6.34011438e+02]
 [ 0.00000000e+00 -0.00000000e+00  1.00000000e+00]]


FileNotFoundError: Folder not found: ./datasets/park_gate